export { default as Dashboard } from './Dashboard'
export { default as Employees } from './Employees'
export { default as Inventory } from './Inventory'
export { default as Records } from './Records'
export { default as Sales } from './Sales'